# models/sources.yml
version: 2

sources:
  - name: dim_tables
    database: JOB_MARKET
    schema: SILVER
    tables:
      - name: DIM_LIEU
        identifier: DIM_LIEU
        description: "Table des dimensions géographiques (code postal, ville…)"
      - name: DIM_CONTRAT
        identifier: DIM_CONTRAT
        description: "Table des dimensions des contrats"
      - name: DIM_CANDIDAT
        identifier: DIM_CANDIDAT
        description: "Table des dimensions des candidats"      
      - name: DIM_ENTREPRISE
        identifier: DIM_ENTREPRISE
        description: "Table des dimensions des entreprises"
      - name: DIM_DOMAINE
        identifier: DIM_DOMAINE
        description: "Table des dimensions des domaines"
      - name: DIM_COMPETENCE
        identifier: DIM_COMPETENCE
        description: "Table des dimensions des competences"
      - name: DIM_ROMECODE
        identifier: DIM_ROMECODE
        description: "Table des dimensions des romecodes"
      - name: DIM_APPELLATION
        identifier: DIM_APPELLATION
        description: "Table des dimensions des appellations"
      - name: DIM_METIER
        identifier: DIM_METIER
        description: "Table des dimensions des metiers"
      - name: DIM_DATE
        identifier: DIM_DATE
        description: "Table des dimensions des dates"
      - name: DIM_STOPWORDS
        identifier: DIM_STOPWORDS
        description: "Table des dimensions des stopwords"
      - name: DIM_SOFTSKILL
        identifier: DIM_SOFTSKILL
        description: "Table des dimensions des stopwords"
      - name: DIM_TYPE_ENTREPRISE
        identifier: DIM_TYPE_ENTREPRISE
        description: "Table des dimensions des stopwords"
      - name: DIM_SENIORITE
        identifier: DIM_SENIORITE
        description: "Table des dimensions des stopwords"
      - name: DIM_TELETRAVAIL
        identifier: DIM_TELETRAVAIL
        description: "Table des dimensions des stopwords"

  - name: gold_tables
    database: JOB_MARKET
    schema: GOLD
    tables:
      - name: FAIT_OFFRE
        identifier: FAIT_OFFRE
        description: "Table des faits à implémenter"
      - name: LIAISON_ROME_METIER_GOLD_SQL
        identifier: LIAISON_ROME_METIER_GOLD_SQL
        description: "Table des liaisons entre romecodes et metiers"
      - name: LIAISON_OFFRE_COMPETENCE
        identifier: LIAISON_OFFRE_COMPETENCE
        description: "Table des liaisons entre offres et competences"
      - name: LIAISON_ROME_SOFT_SKILL_GOLD_SQL

  - name: RAW
    database: JOB_MARKET
    schema: RAW
    tables:
      - name: RAW_OFFRE
        identifier: RAW_OFFRE
        description: "Table d'analyses brutes des offres"
      - name: RAW_OFFRE_CLEAN
        identifier: RAW_OFFRE_CLEAN
        description: "Table d'analyses brutes des offres"
      
        
      - name: RAW_METIER
        identifier: RAW_METIER
        description: "Table brutes des metiers"

      - name: RAW_CANDIDAT
        identifier: RAW_CANDIDAT
        description: "Table brutes des candidats"
