# Notre configuration globale
global:
  scrape_interval: 15s # Par défaut, scrape les cibles toutes les 15 secondes.
  evaluation_interval: 15s # Par défaut, scrape les cibles toutes les 15 secondes.
  # scrape_timeout est défini sur la valeur globale par défaut (10 s).

  # Attachez ces étiquettes à toute série chronologique ou alerte lorsque vous communiquez avec
  # systèmes externes (fédération, stockage distant, Alertmanager).
  external_labels:
    monitor: "my-project"

# Charger et évaluer les règles dans ce fichier toutes les 'evaluation_interval' secondes.
rule_files:
  - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

# Une configuration de scrape contenant exactement un endpoint à scraper :
# Ici, c'est Prometheus lui-même.
scrape_configs:
  # Le nom de la tâche est ajouté en tant qu'étiquette `job=<job_name>` à toutes les séries temporelles extraites de cette configuration.

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    metric_relabel_configs:
    - source_labels: [container_label_com_docker_compose_service]
      target_label: service_name
    - source_labels: [name]
      target_label: container_name

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: 'jm-backend'
    static_configs:
      - targets: ['jm-backend:8081']  
    metrics_path: '/metrics'
