INSERT INTO ONE_BIG_TABLE (
    TITLE,
    DESCRIPTION,
    TYPE_CONTRAT,
    CODE_DOMAINE,
    NOM_DOMAINE,
    CODE_POSTAL,
    VILLE,
    DEPARTEMENT,
    REGION,
    PAYS,
    LATITUDE,
    LONGITUDE,
    POPULATION,
    TYPE_TELETRAVAIL,
    TYPE_SENIORITE,
    CODE_ROME,
    NOM_ENTREPRISE,
    CATEGORIE_ENTREPRISE,
    COMPETENCES,
    TYPES_COMPETENCES,
    SOFTSKILLS_SUMMARY,
    SOFTSKILLS_DETAILS,
    NOM_METIER
  )
VALUES (
    %(title) s,
    %(description) s,
    %(type_contrat) s,
    %(code_domaine) s,
    %(nom_domaine) s,
    %(code_postal) s,
    %(ville) s,
    %(departement) s,
    %(region) s,
    %(pays) s,
    %(latitude) s,
    %(longitude) s,
    %(population) s,
    %(type_teletravail) s,
    %(type_seniorite) s,
    %(code_rome) s,
    %(nom_entreprise) s,
    %(categorie_entreprise) s,
    %(competences) s,
    %(types_competences) s,
    %(softskills_summary) s,
    %(softskills_details) s,
    %(nom_metier) s
  )
RETURNING ID_LOCAL