SELECT id,
  id_local,
  title,
  description,
  type_contrat,
  code_domaine,
  nom_domaine,
  code_postal,
  ville,
  departement,
  region,
  pays,
  latitude,
  longitude,
  population,
  mois_creation,
  jour_creation,
  mois_nom_creation,
  jour_semaine_creation,
  week_end_creation,
  mois_modification,
  jour_modification,
  mois_nom_modification,
  jour_semaine_modification,
  week_end_modification,
  type_teletravail,
  type_seniorite,
  code_rome,
  nom_entreprise,
  categorie_entreprise,
  date_creation_entreprise,
  competences,
  types_competences,
  softskills_summary,
  softskills_details,
  nom_metier
FROM ONE_BIG_TABLE
WHERE {{ "id = :ID" if ID is defined
  else "id_local = :ID_LOCAL" }}
ORDER BY id DESC
LIMIT 1