UPDATE ONE_BIG_TABLE
SET ID_LOCAL = :id_local,
  TITLE = :title,
  DESCRIPTION = :description,
  TYPE_CONTRAT = :type_contrat,
  CODE_DOMAINE = :code_domaine,
  NOM_DOMAINE = :nom_domaine,
  CODE_POSTAL = :code_postal,
  VILLE = :ville,
  DEPARTEMENT = :departement,
  REGION = :region,
  PAYS = :pays,
  LATITUDE = :latitude,
  LONGITUDE = :longitude,
  POPULATION = :population,
  TYPE_TELETRAVAIL = :type_teletravail,
  TYPE_SENIORITE = :type_seniorite,
  CODE_ROME = :code_rome,
  NOM_ENTREPRISE = :nom_entreprise,
  CATEGORIE_ENTREPRISE = :categorie_entreprise,
  COMPETENCES = :competences,
  TYPES_COMPETENCES = :types_competences,
  SOFTSKILLS_SUMMARY = :softskills_summary,
  SOFTSKILLS_DETAILS = :softskills_details,
  NOM_METIER = :nom_metier
WHERE ID = :id
RETURNING *