# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "projet_dbt"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "projet_dbt"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  projet_dbt:
    +python: true

    bronze:
      +materialized: table
      +schema: RAW
      raw_offre:
        +materialized: table
        +schema: RAW
      raw_offre_clean:
        +materialized: table
        +schema: RAW

    # Modèles Silver
    silver:
      +materialized: table
      +schema: SILVER

      src_py:
        +materialized: table
        Match_Lieu_py:
        Match_Contrat_py:
        Match_Entreprise_py:
        Liaison_Rome_Metier_py:
        Liaison_Rome_Soft_Skill_py:
      src_sql:
        +materialized: table
        Match_Lieu_sql:
        Match_Domaine_sql:
        Match_Competence_sql:
        Match_Rome_sql:
        Insert_Candidat:
        Text_Candidat:

    # Modèles Gold
    gold:
      +materialized: table
      +schema: GOLD

      fait_offre_py:
        materialized: table
      liaison_Rome_Metier_gold_sql:
        materialized: table
      liaison_Rome_Soft_Skill_gold_sql:
        materialized: table

    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view

seeds:
  projet_dbt:
    # Seeds dans le schéma RAW
    RAW_OFFRE:
      +schema: RAW

    RAW_ROME_METIER:
      +schema: RAW

    RAW_SOFTSKILL:
      +schema: RAW

    RAW_CANDIDAT:
      +schema: RAW

    # Seeds dans le schéma SILVER
    DIM_LIEU:
      +schema: SILVER

    DIM_TELETRAVAIL:
      +schema: SILVER

    DIM_SENIORITE:
      +schema: SILVER

    DIM_CONTRAT:
      +schema: SILVER

    DIM_ENTREPRISE:
      +schema: SILVER

    DIM_DOMAINE:
      +schema: SILVER
      +column_types:
        id_domaine: number
        code_domaine: varchar
        nom_domaine: varchar

    DIM_COMPETENCE:
      +schema: SILVER

    DIM_METIER:
      +schema: SILVER
      +column_types:
        id_metier: number
        code_appellation: varchar
        nom_appellation: varchar

    DIM_ROMECODE:
      +schema: SILVER
      +column_types:
        id_rome: number
        code_rome: varchar

    DIM_STOPWORDS:
      +schema: SILVER

    DIM_SOFTSKILL:
      +schema: SILVER

    DIM_DATE:
      +schema: SILVER

    DIM_TYPE_ENTREPRISE:
      +schema: SILVER

    DIM_FORMATION:
      +schema: SILVER
