name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test/requirements.txt
        pip install pytest

    - name: Set environment variables
      run: |
        echo "ADZUNA_APP_ID=${{ secrets.ADZUNA_APP_ID }}" >> $GITHUB_ENV
        echo "ADZUNA_APP_KEY=${{ secrets.ADZUNA_APP_KEY }}" >> $GITHUB_ENV
        echo "FRANCE_TRAVAIL_ID=${{ secrets.FRANCE_TRAVAIL_ID }}" >> $GITHUB_ENV
        echo "FRANCE_TRAVAIL_KEY=${{ secrets.FRANCE_TRAVAIL_KEY }}" >> $GITHUB_ENV
        echo "CODE_ROME=${{ secrets.CODE_ROME }}" >> $GITHUB_ENV
        echo "MAX_RESULTS_PER_SOURCE=${{ vars.MAX_RESULTS_PER_SOURCE }}" >> $GITHUB_ENV
        echo "MAX_DAYS_OLD=${{ secrets.MAX_DAYS_OLD }}" >> $GITHUB_ENV
        echo "OUTPUT_DIR=${{ secrets.OUTPUT_DIR }}" >> $GITHUB_ENV

    - name: Run tests with Pytest
      run: |
        cd test
        pytest -v

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image normalizer
      run: docker build -f pipeline/src/Dockerfile.normalizer -t ${{ secrets.DOCKER_USERNAME }}/job-etl-normalizer:latest -t ${{ secrets.DOCKER_USERNAME }}/job-etl-normalizer:${{ github.run_number }} pipeline/src
   
    - name: Build the Docker image snowflake
      run: docker build -f pipeline/src/Dockerfile.snowflake -t ${{ secrets.DOCKER_USERNAME }}/job-etl-snowflake:latest -t ${{ secrets.DOCKER_USERNAME }}/job-etl-snowflake:${{ github.run_number }} pipeline/src

    - name: Build the Docker image DBT
      run: docker build -f snowflake/DBT/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/job-etl-dbt:latest -t ${{ secrets.DOCKER_USERNAME }}/job-etl-dbt:${{ github.run_number }} snowflake/DBT
      
    - name: Push normalizer image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/job-etl-normalizer:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/job-etl-normalizer:${{ github.run_number }}

    - name: Push snowflake image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/job-etl-snowflake:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/job-etl-snowflake:${{ github.run_number }}

    - name: Push DBT image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/job-etl-dbt:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/job-etl-dbt:${{ github.run_number }}
